In [1]:
'''
MariaDB , HeidiSQL Program Connection Code
'''

'\nMariaDB , HeidiSQL Program Connection Code\n'

In [2]:
## 데이터베이스를 사용하기 위해 Python DB API 표준을 따르는 pymysql이라는 모듈 사용
import pymysql
import csv

import pandas as pd
import numpy as np
import re

# 형태소 분석기
from konlpy.tag import *
hannanum = Hannanum()

import sqlite3
import sqlalchemy

In [3]:
from timeit import default_timer as timer
from datetime import timedelta
start = timer()

In [5]:
df_frame = pd.read_excel('File_excel\mpva_event1012.xlsx')
df_frame.columns = ['MNG_NO', 'EVENT_NO', 'DATE_NO', '사건']
df_frame

,MNG_NO,EVENT_NO,DATE_NO,사건
0,950430,1,19220200,박열과 의기투합하여 일본 제국주의에 반대하는 활동을 시작
1,950430,2,19220500,흑도회에 가입
2,950430,3,19220900,박열과 함께 기관지 흑도의 발간책임을 맡음
3,950430,4,19220900,흑우회를 조직해 사상연구와 연설회 등을 추진하면서 기관지 민중 운동을 한글로 발행
4,950430,5,19230400,무정부주의 운동가들을 규합하여 불령사를 조직
5,950430,6,19230900,보호감속 명목으로 도쿄 세타가야 경찰서에 구금
6,950430,7,19260325,대심원 제1특별혀사부에서 이른바 형법 제73조 및 폭발물취제규칙위반 등으로 사형을 ...
7,950430,8,19260400,무기징역으로 감형
8,950430,9,19260723,옥중에서 순국
9,888888,1,19990000,경기도 고양시
10,888888,2,19991111,옥중에서 순국
11,888888,3,19991144,무기징역으로 감형
12,777777,1,19992222,흑도회에 가입

In [8]:
df_frame['MNG_NO'].count()

13

In [6]:
df_evelist = df_frame[['사건']].values.tolist()
ListoStr = ''.join([str(element) for element in df_evelist[0] ])
mpva_evenouns = hannanum.nouns(ListoStr)

# 행 추출
df_1row = df_frame[0:1]
# word라는 새 컬럼 생성
df_evecols = pd.DataFrame(mpva_evenouns)
df_evecols.columns = ['WORD']

# 기존 행과 새로 만든 컬럼의 합성
syn_df = pd.concat([df_1row, df_evecols], axis= 1).fillna(method='pad').drop('사건', axis =1)
syn_df = syn_df.astype({'MNG_NO': 'int'}).astype({'EVENT_NO': 'int'}).astype({'DATE_NO': 'int'})

# append를 통해 다음 행의 값들 추가, 반복문
for i in range(1, df_frame['MNG_NO'].count()):
    ListoStr2 = ''.join([str(element) for element in df_evelist[i] ])
    mpva_evenouns = hannanum.nouns(ListoStr2)

    df_2row = df_frame[i:i+1]
    df_2row.index = ['0']

    df_evecols2 = pd.DataFrame(mpva_evenouns)
    df_evecols2.columns = ['WORD']

    # axis= 0 : 행방향, axis = 열 방향
    syn_df2 = pd.concat([df_2row, df_evecols2], axis= 1).fillna(method='pad').drop('사건', axis =1)
    syn_df2 = syn_df2.astype({'MNG_NO': 'int'}).astype({'EVENT_NO': 'int'}).astype({'DATE_NO': 'int'})

    # 결측치 제거
    syn_df2 = syn_df2.dropna()

    # 행 값 추가
    syn_df = syn_df.append(syn_df2, ignore_index=True)
    
    # 연번
    syn_df["SERIAL_NO"] = syn_df.index + 1

    # 위치 변경
    syn_df = syn_df[['MNG_NO', 'EVENT_NO', 'SERIAL_NO', 'DATE_NO', 'WORD']]
    
syn_df

    MNG_NO  EVENT_NO  SERIAL_NO   DATE_NO       WORD
0   950430         1          1  19220200         박열
1   950430         1          2  19220200       의기투합
2   950430         1          3  19220200         일본
3   950430         1          4  19220200       제국주의
4   950430         1          5  19220200         반대
5   950430         1          6  19220200         활동
6   950430         1          7  19220200         시작
7   950430         2          8  19220500        흑도회
8   950430         2          9  19220500         가입
9   950430         3         10  19220900         박열
10  950430         3         11  19220900        기관지
11  950430         3         12  19220900         흑도
12  950430         3         13  19220900        발간책
13  950430         4         14  19220900        흑우회
14  950430         4         15  19220900         조직
15  950430         4         16  19220900       사상연구
16  950430         4         17  19220900        연설회
17  950430         4         18  19220900          등
18  950430         4         19  19220900         추진
19  950430         4         20  19220900        기관지
20  950430         4         21  19220900          중
21  950430         4         22  19220900         운동
22  950430         4         23  19220900         한글
23  950430         4         24  19220900         발행
24  950430         5         25  19230400      무정부주의
25  950430         5         26  19230400       운동가들
26  950430         5         27  19230400         규합
27  950430         5         28  19230400        불령사
28  950430         5         29  19230400         조직
29  950430         6         30  19230900        보호감
30  950430         6         31  19230900         명목
31  950430         6         32  19230900         도쿄
32  950430         6         33  19230900        경찰서
33  950430         6         34  19230900         구금
34  950430         7         35  19260325        대심원
35  950430         7         36  19260325    제1특별혀사부
36  950430         7         37  19260325         형법
37  950430         7         38  19260325       제73조
38  950430         7         39  19260325  폭발물취제규칙위반
39  950430         7         40  19260325          등
40  950430         7         41  19260325         사형
41  950430         7         42  19260325         선고
42  950430         8         43  19260400       무기징역
43  950430         8         44  19260400         감형
44  950430         9         45  19260723         옥중
45  950430         9         46  19260723         순국
46  888888         1         47  19990000         경기
47  888888         1         48  19990000        고양시
48  888888         2         49  19991111         옥중
49  888888         2         50  19991111         순국
50  888888         3         51  19991144       무기징역
51  888888         3         52  19991144         감형
52  777777         1         53  19992222        흑도회
53  777777         1         54  19992222         가입

In [7]:
# 완성 for문 코드

# 2차 실행 : SERIAL_NO의 값이 알맞게 들어가지 않기 때문에 이 값을 수정해야한다.
# 수정하기 위한 반복문
# 이미 만들어진 syn_df를 이용하여 최종적인 for문을 완성시킨다.

# MNG_NO 값별로의 데이터 갯수를 count() 함수를 이용하여 세기
# 즉, 중복되지 않은 MNG_NO 값별
for j in range(0, df_frame['MNG_NO'].value_counts().count()): 
    
    # copy() : 원천 Dataframe과 별도인 메모리 공간을 파생 Dataframe에 부여하는 것, 
    #          파생 Dataframe에 메모리가 부여되므로 사용 가능한 총 메모리는 줄어들게 된다.
    # 요약 : 메모리 부담 줄임
    # DataFrame.drop_duplicates() : 중복값 처리(unique한 1개의 key만 남기고 나머지 중복은 제거)

    # 밑의 코드를 쉽게 표현하면 df_example = df[0:1].copy()

    # 이미 syn_df에서 만든 dataframe의 범위를 지정해서 final_df_syn으로 다시 재정의한 것
    # 범위 : j번째 MNG_NO의 첫 행 값부터 MNG_NO 번호 1개마다 생성된 'Word'column의 row 갯수까지
    final_df_syn = syn_df[syn_df['MNG_NO'].drop_duplicates().index[j]:syn_df['MNG_NO'].drop_duplicates().index[j]+
                      syn_df['MNG_NO'].drop_duplicates(keep='last').index[j]-syn_df['MNG_NO'].drop_duplicates().index[j]+1].copy()
    
    # 한번 더 반복문을 돌려서 Serial_NO의 값들을 위치에 맞게 재설정함
    k=0
    for k in range(0, syn_df['MNG_NO'].drop_duplicates(keep='last').index[j]-syn_df['MNG_NO'].drop_duplicates().index[j]+1):
        # loc 함수로 조건을 설정하여 연번을 다시 재설정함
        final_df_syn.loc[final_df_syn['SERIAL_NO'] == syn_df['MNG_NO'].drop_duplicates().index[j] + (k+1), 'SERIAL_NO'] = k + 1
    
    print(final_df_syn)

    MNG_NO  EVENT_NO  SERIAL_NO   DATE_NO       WORD
0   950430         1          1  19220200         박열
1   950430         1          2  19220200       의기투합
2   950430         1          3  19220200         일본
3   950430         1          4  19220200       제국주의
4   950430         1          5  19220200         반대
5   950430         1          6  19220200         활동
6   950430         1          7  19220200         시작
7   950430         2          8  19220500        흑도회
8   950430         2          9  19220500         가입
9   950430         3         10  19220900         박열
10  950430         3         11  19220900        기관지
11  950430         3         12  19220900         흑도
12  950430         3         13  19220900        발간책
13  950430         4         14  19220900        흑우회
14  950430         4         15  19220900         조직
15  950430         4         16  19220900       사상연구
16  950430         4         17  19220900        연설회
17  950430         4         18  19220900          등
18  950430         4         19  19220900         추진
19  950430         4         20  19220900        기관지
20  950430         4         21  19220900          중
21  950430         4         22  19220900         운동
22  950430         4         23  19220900         한글
23  950430         4         24  19220900         발행
24  950430         5         25  19230400      무정부주의
25  950430         5         26  19230400       운동가들
26  950430         5         27  19230400         규합
27  950430         5         28  19230400        불령사
28  950430         5         29  19230400         조직
29  950430         6         30  19230900        보호감
30  950430         6         31  19230900         명목
31  950430         6         32  19230900         도쿄
32  950430         6         33  19230900        경찰서
33  950430         6         34  19230900         구금
34  950430         7         35  19260325        대심원
35  950430         7         36  19260325    제1특별혀사부
36  950430         7         37  19260325         형법
37  950430         7         38  19260325       제73조
38  950430         7         39  19260325  폭발물취제규칙위반
39  950430         7         40  19260325          등
40  950430         7         41  19260325         사형
41  950430         7         42  19260325         선고
42  950430         8         43  19260400       무기징역
43  950430         8         44  19260400         감형
44  950430         9         45  19260723         옥중
45  950430         9         46  19260723         순국
    MNG_NO  EVENT_NO  SERIAL_NO   DATE_NO  WORD
46  888888         1          1  19990000    경기
47  888888         1          2  19990000   고양시
48  888888         2          3  19991111    옥중
49  888888         2          4  19991111    순국
50  888888         3          5  19991144  무기징역
51  888888         3          6  19991144    감형
    MNG_NO  EVENT_NO  SERIAL_NO   DATE_NO WORD
52  777777         1          1  19992222  흑도회
53  777777         1          2  19992222   가입

In [7]:
conn = pymysql.connect(host='127.0.0.1', user='root', password='root', db='pythonDB', charset = 'utf8',
                      autocommit=True, cursorclass=pymysql.cursors.DictCursor) 
cur = conn.cursor()

try :
    with cur:
        
        for j in range(0, df_frame['MNG_NO'].value_counts().count()): 
            final_df_syn = syn_df[syn_df['MNG_NO'].drop_duplicates().index[j]:syn_df['MNG_NO'].drop_duplicates().index[j]+
                      syn_df['MNG_NO'].drop_duplicates(keep='last').index[j]-syn_df['MNG_NO'].drop_duplicates().index[j]+1].copy()
    
            k=0
            for k in range(0, syn_df['MNG_NO'].drop_duplicates(keep='last').index[j]-syn_df['MNG_NO'].drop_duplicates().index[j]+1):
                final_df_syn.loc[final_df_syn['SERIAL_NO'] == syn_df['MNG_NO'].drop_duplicates().index[j] + (k+1), 'SERIAL_NO'] = k + 1
            
            # 기존 코드에서 sql insert하는 코드를 추가한 것
            db_engine = sqlalchemy.create_engine("mysql+pymysql://{user}:{password}@localhost/{db}".format(user='root', password='root', db='pythonDB'))
            # DataFrame Insert 구문
            final_df_syn.to_sql('book_merit_ghev', db_engine, if_exists ='append', index=False)
                
            conn.commit()
except:
    print('Error')
                
finally :
    end = timer()
    print(timedelta(seconds= end-start))
    conn.close()

0:00:19.407340