In [1]:
import pandas as pd
import re

In [2]:
sm_area = pd.read_excel('공훈록 전체_JH.xlsx', sheet_name= "Sheet3")
sm_area

,MNG_NO,NAME_KO,WORKOUT_AFFIL,CONTENT
0,80802,문길환,학생운동,1929년 12월 부산제2공립상업학교 재학 중 광주학생운동에 호응하는 동맹휴교를 계...
1,42952,이철주,학생운동,1940년 11월 경기중학교 재학 중 동창생 마츠하라[松原博]와 가회동(嘉會洞) 자...
2,41893,이권재,학생운동,1940년대 초반 일본 제국주의 타도를 위해 비밀결사를 조직하여 활동하다 체포되어 ...
3,40943,김종윤,학생운동,1940년 11월 서울 경기공립중학교 제5학년 재학 중 비밀결사 조선인해방투쟁동맹에...
4,50673,이세원,학생운동,충남 예산(禮山) 사람이다.\n1929년 서울 협성실업학교(協成實業學校) 3학년에 ...
...,...,...,...,...
671,957797,최심,학생운동,1929년 11월 전남 광주에서 광주여자고등보통학교 재학 중 광주학생운동에 참여하였...
672,957800,이정,학생운동,1929년 11월 전남 광주여자고등보통학교 재학 중 광주학생운동 동조시위에 참여했다...
673,964648,정창희,학생운동,1930년 1월 충남 예산공립농업학교(禮山公立農業學校) 2학년 재학 중 광주학생운동...
674,964753,최용식,학생운동,1930년 전남 여수에서 여수공립수산학교 재학 중 맹휴주도자로 활동하다 퇴학 처분을...
675,964896,고정불,학생운동,1930년 전남 여수공립수산학교 재학 중 일본인 교사 배척 및 노예적 교육 철폐 등...

In [10]:
sm_alist = sm_area['CONTENT'][0].split('.')
sm_list = []

# 문장에 '광주'라는 단어가 들어가있으면, 리스트에 하나씩 추가한다.
for x in sm_alist:
    if "광주" in x:
        sm_list.append(x)
sm_st = ','.join(sm_list)
sm_st = re.sub(r'[(\u4e00-\u9fff)]+', "" , sm_st)
m = re.findall('광주', sm_st)
sm_rarea = pd.DataFrame({     'MNG_NO' : sm_area['MNG_NO'][0],
                            'NAME_KO' : sm_area['NAME_KO'][0],
                            'WORKOUT_AFFIL' : sm_area['WORKOUT_AFFIL'][0],
                            'SCHOOL' : m })

for zz in range(1, sm_area['MNG_NO'].count()):
    
    # NAME_KO 두 번째 인물 출력
    # 위의 코드와 동일하고, 중복 제거하는 코드만 추가되어있다.
    sm_t_list2 = sm_area['CONTENT'][zz].split('.')
    sm_list2 = []

    for y in sm_t_list2:
        if "광주" in y:
            sm_list2.append(y)
    # print(sm_list2)
    # len(sm_list)

    sm_st2 = ','.join(sm_list2)
    sm_st2 = re.sub(r'[(\u4e00-\u9fff)]+', "" , sm_st2)
    m2 = re.findall('광주', sm_st2)

    # 리스트 내 중복된 단어 제거
    arr_m = []
    for v in m2:
        if v not in arr_m:
            arr_m.append(v)
    arr_m

    sm_rarea2 = pd.DataFrame({     'MNG_NO' : sm_area['MNG_NO'][zz],
                                'NAME_KO' : sm_area['NAME_KO'][zz],
                                'WORKOUT_AFFIL' : sm_area['WORKOUT_AFFIL'][zz],
                                'SCHOOL' : arr_m })
    sm_rarea = sm_rarea.append(sm_rarea2, ignore_index= True)
    sm_rarea
print(sm_rarea)

     MNG_NO NAME_KO WORKOUT_AFFIL SCHOOL
0     80802     문길환          학생운동     광주
1     50673     이세원          학생운동     광주
2     50622     윤옥분          학생운동     광주
3     50626     윤해병          학생운동     광주
4     50632     이강후          학생운동     광주
..      ...     ...           ...    ...
344  964396     김우곤          학생운동     광주
345  964479     강봉근          학생운동     광주
346  957797      최심          학생운동     광주
347  957800      이정          학생운동     광주
348  964648     정창희          학생운동     광주

[349 rows x 4 columns]